In [89]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [94]:
data = pd.read_excel('listings editted.xlsx')
data

,id,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,property_type,room_type,...,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,Unnamed: 44,sentiment_pre,sentiment_post,sentiment_overall
0,2595,0.80,0.17,0.0,8.0,8.0,1.0,1.0,Entire rental unit,Entire home/apt,...,0,3,3,0,0,0.33,NaN,0.686350,NaN,0.795956
1,3831,0.09,0.69,0.0,1.0,1.0,1.0,1.0,Entire guest suite,Entire home/apt,...,0,1,1,0,0,4.86,NaN,0.805954,0.717229,NaN
2,5121,1.00,1.00,0.0,1.0,1.0,1.0,1.0,Private room in rental unit,Private room,...,0,2,0,2,0,0.52,NaN,0.934500,NaN,0.886122
3,5136,1.00,0.25,0.0,1.0,1.0,1.0,1.0,Entire rental unit,Entire home/apt,...,0,1,1,0,0,0.02,NaN,NaN,0.983300,NaN
4,5178,1.00,1.00,0.0,1.0,1.0,1.0,0.0,Private room in rental unit,Private room,...,0,1,0,1,0,3.68,NaN,0.743043,0.718419,0.766565
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38272,53662330,0.97,1.00,0.0,1.0,1.0,1.0,1.0,Private room in residential home,Private room,...,0,6,0,6,0,NaN,NaN,NaN,NaN,NaN
38273,53662542,0.97,1.00,0.0,1.0,1.0,1.0,1.0,Private room in residential home,Private room,...,0,6,0,6,0,NaN,NaN,NaN,NaN,NaN
38274,53662772,0.94,1.00,0.0,10.0,10.0,1.0,1.0,Private room in serviced apartment,Private room,...,1,13,0,13,0,NaN,NaN,NaN,NaN,NaN
38275,53663081,0.94,1.00,0.0,10.0,10.0,1.0,1.0,Private room in serviced apartment,Private room,...,1,13,0,13,0,NaN,NaN,NaN,NaN,NaN
38276,53665099,1.00,0.97,0.0,108.0,108.0,1.0,1.0,Entire rental unit,Entire home/apt,...,1,1,1,0,0,NaN,NaN,NaN,NaN,NaN

In [95]:
data = data.dropna(subset=['sentiment_overall'])
data.fillna(0, inplace=True)
data.fillna(0)
data

/Users/zeping/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4462: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(

,id,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,property_type,room_type,...,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,Unnamed: 44,sentiment_pre,sentiment_post,sentiment_overall
0,2595,0.8,0.17,0.0,8.0,8.0,1.0,1.0,Entire rental unit,Entire home/apt,...,0,3,3,0,0,0.33,0.0,0.686350,0.000000,0.795956
2,5121,1.0,1.00,0.0,1.0,1.0,1.0,1.0,Private room in rental unit,Private room,...,0,2,0,2,0,0.52,0.0,0.934500,0.000000,0.886122
4,5178,1.0,1.00,0.0,1.0,1.0,1.0,0.0,Private room in rental unit,Private room,...,0,1,0,1,0,3.68,0.0,0.743043,0.718419,0.766565
5,5203,0.0,0.00,0.0,1.0,1.0,1.0,1.0,Private room in rental unit,Private room,...,0,1,0,1,0,0.87,0.0,0.930761,0.000000,0.922601
6,5803,1.0,1.00,1.0,3.0,3.0,1.0,1.0,Private room in townhouse,Private room,...,0,3,1,2,0,1.48,0.0,0.912257,0.906244,0.929523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1802,1910270,1.0,0.67,0.0,2.0,2.0,1.0,1.0,Entire residential home,Entire home/apt,...,0,1,1,0,0,0.25,0.0,0.000000,0.000000,0.899386
1803,1913540,0.0,0.00,0.0,1.0,1.0,1.0,1.0,Entire rental unit,Entire home/apt,...,0,1,1,0,0,0.02,0.0,0.000000,0.000000,0.931700
1804,1914185,0.0,0.00,0.0,1.0,1.0,1.0,1.0,Entire rental unit,Entire home/apt,...,0,1,1,0,0,0.41,0.0,0.000000,0.000000,0.821725
1805,1914231,1.0,0.86,0.0,1.0,1.0,1.0,0.0,Entire rental unit,Entire home/apt,...,0,1,1,0,0,4.04,0.0,0.000000,0.880250,0.772178
1807,1918693,1.0,0.93,1.0,1.0,1.0,1.0,1.0,Private room in townhouse,Private room,...,0,1,0,1,0,3.06,0.0,0.000000,0.000000,0.945343

In [96]:
X = data[['host_response_rate', 'host_acceptance_rate', 'host_is_superhost', 'host_total_listings_count', 'host_identity_verified', 'accommodates', 'bedrooms', 'beds','price','minimum_nights_avg_ntm','maximum_nights_avg_ntm','instant_bookable','calculated_host_listings_count','reviews_per_month']]
y_sent = data['sentiment_overall']
X_train, X_test, y_sent_train, y_sent_test = train_test_split(X, y_sent, test_size = 0.2)

In [97]:
regr = RandomForestRegressor(max_depth=2, random_state=0)
regr_sent = regr.fit(X_train, y_sent_train)
regr_sent.feature_importances_
y_sent_test_pred = regr_sent.predict(X_test)
pd.DataFrame(list(X),list(regr_sent.feature_importances_))

                                       0
0.039244              host_response_rate
0.022640            host_acceptance_rate
0.000944               host_is_superhost
0.013339       host_total_listings_count
0.055594          host_identity_verified
0.033675                    accommodates
0.012477                        bedrooms
0.066640                            beds
0.066657                           price
0.124974          minimum_nights_avg_ntm
0.028137          maximum_nights_avg_ntm
0.052885                instant_bookable
0.009503  calculated_host_listings_count
0.473291               reviews_per_month

In [98]:
mse_sent_rf = mean_squared_error(y_sent_test_pred, y_sent_test)
mse_sent_rf

0.020542406002926113

In [104]:
r2_sent_rf = r2_score(y_sent_test,y_sent_test_pred)
r2_sent_rf

0.004988660694898894

In [100]:
y_rating = data['review_scores_rating']
X_train, X_test, y_rating_train, y_rating_test = train_test_split(X, y_rating, test_size = 0.2)
regr_rating = regr.fit(X_train, y_rating_train)
regr_rating.feature_importances_
y_rating_test_pred = regr_rating.predict(X_test)
pd.DataFrame(list(X),list(regr_rating.feature_importances_))

                                       0
0.015593              host_response_rate
0.013297            host_acceptance_rate
0.004955               host_is_superhost
0.015462       host_total_listings_count
0.000000          host_identity_verified
0.049730                    accommodates
0.121452                        bedrooms
0.082105                            beds
0.137659                           price
0.049769          minimum_nights_avg_ntm
0.052225          maximum_nights_avg_ntm
0.000000                instant_bookable
0.040731  calculated_host_listings_count
0.417023               reviews_per_month

In [101]:
mse_rating_rf = mean_squared_error(y_rating_test_pred, y_rating_test)
mse_rating_rf

0.054658556036184684

In [105]:
r2_rating_rf = r2_score(y_rating_test,y_rating_test_pred)
r2_rating_rf

-0.36269116091365783